### ISSUE TITLE
maybe skip "average number of edits per contributor" for 2006/2007

### ISSUE THREAD

**Issue by matkoniecz** [piebro/OpenStreetMap-Statistics#1]
https://piebro.github.io/openstreetmap-statistics/#a3ed graph focuses on massive outlier in 2006/2007

![screen01](https://user-images.githubusercontent.com/899988/203820850-4f5f5b97-7d42-4617-a138-61bd9f0c088d.png)

**Comment by piebro** [comment]
That's true, but I think it's the spikes also shows quite well that there were many data imports at the beginning of OSM which I think is nice and it's always possible to select a certain time range by dragging the mouse in the plot and remove the outlier.

![screenshot](https://user-images.githubusercontent.com/17904272/203830016-b3073d67-c4ad-46cf-bbc8-f06c8c9f0630.png)

![average_number_of_edits_per_contributor_per_month](https://user-images.githubusercontent.com/17904272/203830006-a9d42925-3184-475a-887f-6092e13430a5.png)
