### ISSUE TITLE
how StreetComplete has 72 000 mappers in 2022 and 55 000 in total?

### ISSUE THREAD

**Issue by matkoniecz** [piebro/OpenStreetMap-Statistics#102]
https://piebro.github.io/openstreetmap-statistics/#c229

See bottom line on the image

![screen](https://github.com/piebro/openstreetmap-statistics/assets/899988/595b4d54-a9cf-447e-b9e7-1ce55517e36f)

**Comment by piebro** [comment]
Thanks a lot, that seems like a bug and I'm not sure yet how it happens. I will look into it once I find the time. Thanks for reporting, these things are sometimes easy to miss, but it's important for me that the data is correct.
