### ISSUE TITLE
https://piebro.github.io/openstreetmap-statistics/#6773 is down

### ISSUE THREAD

**Issue by matkoniecz** [piebro/OpenStreetMap-Statistics#14]
https://piebro.github.io/openstreetmap-statistics/#6773 

![screen20](https://user-images.githubusercontent.com/899988/203981511-78805526-8f7f-4ca1-91b8-5f9a489ebf85.png)

![screen19](https://user-images.githubusercontent.com/899988/203981456-cd5674fd-e9b3-4b90-ad1c-545de34fa97d.png)

**Comment by piebro** [comment]
Thanks, I pushed the changes to index.html without updating data.js and forgot that it will break. I'll fix this.

**Comment by piebro** [comment]
It's working again. I will update data.js with github actions in the branch and then merge it again.
