### ISSUE TITLE
Is it possible to not show line where usage is exactly 0?

### ISSUE THREAD

**Issue by matkoniecz** [piebro/OpenStreetMap-Statistics#27]
See say https://piebro.github.io/openstreetmap-statistics/#eb30

teal for posiki failed import is spread on 0 across entire bottom of graph. Maybe it is possible to set to `None` rather `0` values where usage is literally 0?

To allow distinguish low usage from completely and utterly missing usage?

**Comment by piebro** [comment]
I know what you mean, but I think this is kind of the 'normal' way of plotting the data. Not showing the line there would be more confusing. Also I think it's not really an issue for most plots.
