### ISSUE TITLE
stable colours for editing software graph

### ISSUE THREAD

**Issue by matkoniecz** [piebro/OpenStreetMap-Statistics#28]
It would be so nice to have the same colour for JOSM, iD etc on both on https://piebro.github.io/openstreetmap-statistics/#6320

https://github.com/piebro/openstreetmap-statistics/blob/master/src/add_topic_editing_software.py

![screen21](https://user-images.githubusercontent.com/899988/204095216-91e6f4f1-4f9e-4027-89ca-cc058d32a748.png)

**Comment by matkoniecz** [comment]
sorry for opening so many issues, feel free to WONTFIX and close them or add "PR welcome" label

**Comment by piebro** [comment]
> sorry for opening so many issues, feel free to WONTFIX and close them or add "PR welcome" label

Don't feel sorry, I really appropriate the feedback and every opened issue, keep them coming :blush:. PR are definitely welcome, I might add some labels to issues, but I also do have some spare time to add some stuff myself.

**Comment by piebro** [comment]
> It would be so nice to have the same colour for JOSM, iD etc on both on https://piebro.github.io/openstreetmap-statistics/#6320

Yes that's true. It would make it easier to compare the graphs to each other. It should be possible but might be a little tricky to implement

**Comment by matkoniecz** [comment]
Thanks!
