### ISSUE TITLE
Make it possible to sort the results in tables by year

### ISSUE THREAD

**Issue by deevroman** [piebro/OpenStreetMap-Statistics#33]
This is the only thing missing from the [wiki statistics](https://wiki.openstreetmap.org/wiki/Editor_usage_stats):
<img width="756" alt="Снимок экрана 2022-11-29 в 12 31 21" src="https://user-images.githubusercontent.com/25708359/204491910-9b43baa3-ef95-480f-99e3-2423a4ce54cc.png">

**Comment by piebro** [comment]
That's a good idea and makes the tables more useful, thanks! I will look into how to implement this.

**Comment by piebro** [comment]
b98bb556acf824eb429d80e6cfef0d7b3ae6f5df adds tables
