### ISSUE TITLE
Average edits per contributor and edits count y-axis between 2006 and 2008

### ISSUE THREAD

**Issue by le-jun** [piebro/OpenStreetMap-Statistics#35]
I’m not sure to understand it’s source, but the plots of average edits per contributors and edits counts are kind of unusable because of the y-axis scaling on some strangely high values between 2006 and 2008 :

* Are those spikes an error? Where do they originate from?
* Would it be possible to cut those values off for readable plots by default?

**Comment by stalker314314** [comment]
Maybe both of these plot should use median rather than average? Averages are heavily skewed (in my opinion). Just 2c

**Comment by piebro** [comment]
Yes that's a good idea, thanks! I will check out using the median for the plot and maybe for others where it would make more sense too.

>     * Are those spikes an error? Where do they originate from?

The data should be correct, I think it's because at the beginning of OSM there were a lot of data imports with may edits from only a few people.

**Comment by matkoniecz** [comment]
See also #1
