### ISSUE TITLE
add "total contributors per month except maps.me"

### ISSUE THREAD

**Issue by matkoniecz** [piebro/OpenStreetMap-Statistics#4]
or "total contributors per month with >1000 edits"?

see https://wiki.openstreetmap.org/wiki/File:New_contributors_month_split.png - contributor count seems stagnating while it is actually effect of wave of MAPS.ME activity slowly disappearing

**Comment by piebro** [comment]
That's interesting, yes I think both statistics are interesting and should be added. There could also be a small text with some explanations for the "total contributors per month except maps.me" plot.

**Comment by piebro** [comment]
added the two plots with the pull request #23
