### ISSUE TITLE
"How popular is each editing software by month" should be "percent stacked"

### ISSUE THREAD

**Issue by westnordost** [piebro/OpenStreetMap-Statistics#52]
["How popular is each editing software by month"](https://piebro.github.io/openstreetmap-statistics/#158c) should be shown as a "percent stacked" graph, just like ["What's the market share of edits per month"](https://piebro.github.io/openstreetmap-statistics/#a008).

Also, in my opinion, for percent-stacked graphs, it is better to only draw the area and not the line (because the line is drawn with a certain fixed thickness and over areas, i.e. also over the area actually "owned" by another row).

**Comment by matkoniecz** [comment]
> ["How popular is each editing software by month"](https://piebro.github.io/openstreetmap-statistics/#158c) should be shown as a "percent stacked" graph

Note that it does not sum to 100% as people may use multiple editors.

Imagine world where only SC and JOSM exist, initially all people use JOSM then all people started to use JOSM and SC.

In current graph JOSM would have continued 100% (correctly), in stacked one JOSM would fall to 50% despite that all people still use it.

**Comment by westnordost** [comment]
Right.
