### ISSUE TITLE
imagery usage graph is just graph of iD use

### ISSUE THREAD

**Issue by matkoniecz** [piebro/OpenStreetMap-Statistics#6]
https://piebro.github.io/openstreetmap-statistics/#4f2c

https://piebro.github.io/openstreetmap-statistics/#a008

![monthly_edits_that_use_at_least_one_imagery_service](https://user-images.githubusercontent.com/899988/203866682-a5736bb5-a1d9-4d93-9bae-4b3c6357894f.png)
![market_share_of_edits_per_month](https://user-images.githubusercontent.com/899988/203866686-d279d48d-203b-4e49-b170-d46e2cd30bdc.png)

is https://github.com/piebro/openstreetmap-statistics/blob/master/src/add_topic_imagery_service.py just looking for iD specific `imagery` changeset tag?

What bout iD users who have not used imagery and JOSM users who used source tag?

**Comment by piebro** [comment]
That's interesting. I misunderstood the imagery tag (here is the explanation: https://wiki.openstreetmap.org/wiki/Key:imagery_used). Maybe the the title and questing wording should be a little different, explaining which editors are using the tag by default.

**Comment by matkoniecz** [comment]
Added

> Note that some editors like [JOSM](https://wiki.openstreetmap.org/wiki/JOSM) are not setting it.

to that page.

As iD is always setting it (except rare cases where user disabled imagery) and JOSM is basically never setting it (unless user added it manually) this graph will basically graph iD popularity.

There are other editors using it ([Vespucci](https://wiki.openstreetmap.org/wiki/Vespucci), and [Go Map!!](https://wiki.openstreetmap.org/wiki/Go_Map!!)), but their popularity is quite low by edit volume.

**Comment by matkoniecz** [comment]
per https://github.com/piebro/openstreetmap-statistics/pull/11#issuecomment-1327161916 it is welcome to submit PR removing it

**Comment by piebro** [comment]
I thought about it again and I think I will keep the "monthly edits that use at least one imagery service" although it basically the plot of edit with iD. I think this is still interesting since that way people can see for themself that imagery service usage basically means iD usage and maybe it will change in the future. I think the plot is also ok for the sake of completeness.

**Comment by matkoniecz** [comment]
@piebro In such case may addding note similar to

> This graph is based on `imagery` tag set automatically by iD, Vespucci and Go Map!!. As other editors are not using it and iD is vastly more popular than other relevant editors this graph is very close to "market share of iD by edit volume".
> JOSM users are typically using `source` field to note actually used sources


would be helpful?

**Comment by piebro** [comment]
Yes I think that's a good addition. It might also be interesting to have a look at the source tag of JOSM. Do you know if JOSM it the only editor that uses the tag and how it uses it?

**Comment by matkoniecz** [comment]
Vespucci allows to fill it: https://www.openstreetmap.org/changeset/129726146

iD has some mediocre support for it and is barely used https://www.openstreetmap.org/changeset/129757782

StreetComplete fills it automatically based on GPS location: https://www.openstreetmap.org/changeset/129749863

https://wiki.openstreetmap.org/wiki/Key:source has some info

As it is often freeform it would be harder to parse it
