### ISSUE TITLE
Add more links

### ISSUE THREAD

**Issue by piebro** [piebro/OpenStreetMap-Statistics#64]
There is an easy way to add more links (add them to the json file [here](https://github.com/piebro/openstreetmap-statistics/blob/master/src/links.json)). I think it has value to add links to the most common editing software, most common (imagery) sources or bots.

**Comment by westnordost** [comment]
Some could be sourced from here:
https://github.com/Zverik/editor-stats/blob/master/EDetect.pm#L176-L196

**Comment by matkoniecz** [comment]
links seems visible in https://piebro.github.io/openstreetmap-statistics/#c229

**Comment by piebro** [comment]
> Some could be sourced from here: https://github.com/Zverik/editor-stats/blob/master/EDetect.pm#L176-L196

Yes, that's a good idea, thanks! I think it's also interesting how the editors are determined at https://github.com/Zverik/editor-stats/blob/master/EDetect.pm#L9-L133 . For example "wheelmap.org" => "'rosemary" and that probably makes sense.

Maybe the logic for these things can be added in some easy to change config/JSON file. This way it would be easier for people add and fix things without having to dig into the code. And I think it would be good for more visibility/transparency to know how this is handled.

**Comment by piebro** [comment]
> links seems visible in https://piebro.github.io/openstreetmap-statistics/#c229

I'm not sure what you mean.

**Comment by matkoniecz** [comment]
> I'm not sure what you mean.

Provided links are used in the table visible at the linked page

**Comment by piebro** [comment]
I reworked the linking and filtering and open a new issue [here](https://github.com/piebro/openstreetmap-statistics/issues/73) to add more links and filter rules.
