### ISSUE TITLE
Add attrition rate?

### ISSUE THREAD

**Issue by matkoniecz** [piebro/OpenStreetMap-Statistics#8]
It can be for example set of graphs showing % of users active among ones that made first edit in year X

**Comment by piebro** [comment]
That's a cool idea. The plot can answer the question: `How many contributors with their first edit in year X also contributed in the last (12 month)?` It could be one line plot. The x axis could be `years` and y axis could be `%`.

**Comment by matkoniecz** [comment]
Maybe something like https://www.statista.com/statistics/921152/mobile-android-version-share-worldwide/ ?

With y being market share among JOSM users and colours having meaning like "first JOSM edit in 2012", "first JOSM edit in 2013"...

![screen19](https://user-images.githubusercontent.com/899988/205630631-e013a3da-a6fd-4e0d-a637-5a6a56cdc9b4.png)

Or even better - make y total JOSM user count (so it may go up and down - and make more clear whether influx is replacing disappearing users or whether original mappers are present or disappearing)

-------------------------

Obviously, it can be also done for all users.

**Comment by piebro** [comment]
That's a cool graphic and I think it should work. I'm not sure how it will look, because there will be about 18 different colors if we choose a color for each year. I will test how it looks or if it is necessary to merge everything older then 10 years for example

**Comment by matkoniecz** [comment]
> I'm not sure how it will look, because there will be about 18 different colors if we choose a color for each year

colours can repeat after say 10 were used - I expect it to remain readable

**Comment by piebro** [comment]
#93 adds statistics about the attrition rate here: https://piebro.github.io/openstreetmap-statistics/#d993
It looked a little messy using all the years, that's why I added a range of two years. I think it works out. What do you think?

**Comment by matkoniecz** [comment]
Would it be maybe possible to show edit count (or user count) for each year pair as a separate line on a line graph?

So it could be seen how quickly it drops down?

Maybe also normalize it to the max of series and shift them so different years start from the same point on graph and it can be compared?

**Comment by matkoniecz** [comment]
Right now it is a bit tricky to answer from graphs how quickly people disappear.

But I like counting edits, not people - that avoids bias toward single edit-accounts and similar that would, in a way, overestimate attrition. Though showing also that can be interesting.

**Comment by piebro** [comment]
> Would it be maybe possible to show edit count (or user count) for each year pair as a separate line on a line graph?

Yes, I thought about it too, but I'm not very happy with how it looks. I might still be informative though.
![general_contributor_count_attrition_rate_yearly](https://user-images.githubusercontent.com/17904272/236870108-f84ebc9e-d073-4a09-8039-255c43bb73c2.png)

> Maybe also normalize it to the max of series and shift them so different years start from the same point on graph and it can be compared?

That is interesting. I created the plot in this [web notebook](https://piebro.github.io/openstreetmap-statistics/jupyter_lite/retro/notebooks/?path=custom_plots_browser.ipynb), but I think the plot also looks messy. If I select only 3-4 year ranges it's fine, but I think it's hard to see something when they are all together. Do you have any ideas how to clean up the plot?

![Screenshot from 2023-05-08 18-04-29](https://user-images.githubusercontent.com/17904272/236873360-4575c09a-d6ca-4f90-9601-fdc8038c9fb0.png)

**Comment by matkoniecz** [comment]
> Yes, I thought about it too, but I'm not very happy with how it looks. I might still be informative though.

Maybe it is not very pretty but gives some interesting info, I think

> Do you have any ideas how to clean up the plot?

Drop zero entry, I guess?

2005-2006 cohort hitting 1 again is a bit weird, but I guess that it could be just few people.

And overall it is really noisy. But shows how retention changes (for worse in recent years) over time

BTW, I was unable to run it, maybe due to

> Uncaught (in promise) Error: Canceled future for kernel_info_request message before replies were done

shown in browser console

**Comment by piebro** [comment]
> Maybe it is not very pretty but gives some interesting info, I think

Yes, I will just add it at the bottom.

> But shows how retention changes (for worse in recent years) over time

True, Especially the last three cohorts.

> Drop zero entry, I guess?

I tried it and it still looks noisy. I think I will just add the first plot. The trends can be seen there too.

> BTW, I was unable to run it, maybe due to

Ok, it works for me on firefox and chrome. Does the [example notebook](https://jupyterlite.readthedocs.io/en/latest/_static/retro/notebooks/?path=python.ipynb) from jupyter lite from which this is based on work?

**Comment by matkoniecz** [comment]
> Ok, it works for me on firefox and chrome. Does the [example notebook](https://jupyterlite.readthedocs.io/en/latest/_static/retro/notebooks/?path=python.ipynb) from jupyter lite from which this is based on work?

no and console log is filled with errors about failing websockets

**Comment by piebro** [comment]
Well, then it might be something with jupyter lite and your browser or browser settings, I'm not sure. Alternatively you can also use [this](https://github.com/piebro/openstreetmap-statistics/blob/master/src/custom_data_and_plots.ipynb) notebook to create plots locally with python if you want to.

**Comment by matkoniecz** [comment]
Third graph at https://piebro.github.io/openstreetmap-statistics/#63f6 is also really interesting/worrying

**Comment by piebro** [comment]
Why do you think so? I think the distribution of editors each month with many or few total edits is fine.

**Comment by piebro** [comment]
the same plot but with number of edits might be interesting. My guess would be that editors with with many edits contribute a lot more in edits each month.

**Comment by matkoniecz** [comment]
> Why do you think so? I think the distribution of editors each month with many or few total edits is fine.

https://piebro.github.io/openstreetmap-statistics/#63f6 seems to show that count of highly active mappers is declining, though it may be result of COVID having anomalously high activity

**Comment by piebro** [comment]
Yes, all mapping activity seems to decline and all type of mappers in a similar pace. I think COVID had a big impact (It would be interesting to look into it in more detail) and maybe at least in some regions, there is less mapping activity because most stuff is already mapped and the map is maintained by fewer people in these regions resulting in fewer edits.
