### ISSUE TITLE
Maybe add an age of active accounts stats

### ISSUE THREAD

**Issue by matkoniecz** [piebro/OpenStreetMap-Statistics#9]
Something like: 20% of accounts that made edit in 2022 signed up in 2022, 10% in 2021, etc

Maybe add also filtering by editor? 20% of accounts that made edit in 2022 using JOSM signed up in 2022, 10% in 2021, etc

**Comment by piebro** [comment]
I was thinking about plotting usage of (new) users before but I wasn't sure what kind of question would be interesting.
Maybe:

General => "How many people are contributing each month" ([here](https://piebro.github.io/openstreetmap-statistics/#63f6)):
- add new plot "new contributors per month" (amount of contributors with their first edit monthly)

Editing Software => "How many people are contributing per editing software each month?" ([here](https://piebro.github.io/openstreetmap-statistics/#c229)):
- add a new plot "monthly new contributor count per editing software" (amount of contributors per editing software with their first edit in total (or with this software?) monthly)

Do you think a yearly table for editing software (with all top 100) in addition to the plot is also interesting? if so, it should probably be an other question I think.
